version: '3.7'

volumes:
  postgres-data:

services:
  web:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host 0.0.0.0
    ports:
    - 5000:5000
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: library/postgres:12.0
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
    - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
